### ISSUE TITLE
Inquire regarding Phasing Correction and LAI results

### ISSUE THREAD

**Issue by guidebortoli** [AI-sandbox/gnomix#17] opened 2021-12-15 15:47 UTC
Hi,

I have been doing some LAI tests and I have some inquires regarding the outputs that I need some help understanding:

I have performed a Gnomix with the TRUE option for the Phasing correction enabled as well as with FALSE. I have also turned the option to generate the .lai file, which gives the ancestry per marker.

When I open the file .lai from the inference done with the TRUE option enabled for the phasing correction, I can see that the markers are randomly sorted. Why is it randomly sorted that way?
Also, when I take this .lai file from above and I sort the positions to reflect the same order as in the .lai file from the FALSE ran (for phasing correction), I noticed that some markers are assigned with completely different ancestry. I was expecting not a change in the ancestry assigned, but just a switch of the phase when turning the TRUE option on.

I don't know if that is something related to the fact that whenI ran with the TRUE option on I see that the .msp file has fixed windows, while for FALSE, the windows are different sizes... 

Thanks,

Guilherme

**Comment by weekend37** [comment] 2021-12-15 16:38
Hi Guide, 

Thanks for all the comments. It helps us making this software more accessible for other users.

### Regarding the random sorting:
That's not supposed to be that way. As disclaimed on the README, this feature is in beta mode (as it was made specifically for you). I will look into this and fix this if I can reproduce this behavior. 

### Regarding the new ancestry predictions with the phasing flag on:
This **can** happen. The LAI-phasing error correction iteratively makes swaps along the chromosome and re-evaluates the  ancestry estimates for that given assignment. Therefore, there's a chance that the most likely ancestry for a given segment at every iteration. With that being said, it should not be much different (either much different ancestries or long segments changing) from the ancestry calls estimated without any additional phasing. This could also be a derivative of the random sorting of the markers mentioned above. If you think that the change is large and it persists after fixing the random sorting, please let me know and we can look into that.

### Regarding the varying window size for the .msp files:
This is a concern and is a bug if turns out to be true. I will look into it and fix if I can reproduce this behavior. 

 I will keep you posted in this thread.
 Thanks again.

**Comment by weekend37** [comment] 2021-12-15 17:01
Are you using one of our trained models or training your own model?

**Comment by guidebortoli** [comment] 2021-12-15 17:05
HI @weekend37 
I'm using my own training model.
I have done some tests comparing the global ancestry for on chromosome only, comparing gnomix with the TRUE and the FALSE options on the output from RFMIX2 and they correlate well. I was having problems before (as we discussed in another post), but once I subset the markers from my query to the reference file to train the model, it worked. But that's a past issue...
Not sure if this helps...

Thanks,

**Comment by weekend37** [comment] 2021-12-15 17:18
This helps a lot, thanks.

**Comment by guidebortoli** [comment] 2022-01-04 19:20
Hi @weekend37. First and foremost, happy new year to all of you. 
Have you had any chance to take a look into this matter?

Thanks,

Guilherme

**Comment by weekend37** [comment] 2022-01-05 18:00
Hi Guilherme. Yes.

I fixed the random ordering of markers in the .lai file. please pull and confirm that it works

However, I couldn’t reproduce the .msp file behavior that you described so perhaps you can check once more and if it persists you can maybe send me files to reproduce it.

**Comment by guidebortoli** [comment] 2022-01-12 14:00
Hi @weekend37 thanks,
I've got an error trying to run it:

...
--------------------------------------------------------------------------------
-----------------------------------  Gnomix  -----------------------------------
--------------------------------------------------------------------------------
When using this software, please cite: 
Helgi Hilmarsson, Arvind S Kumar, Richa Rastogi, Carlos D Bustamante, 
Daniel Mas Montserrat, Alexander G Ioannidis: 
"High Resolution Ancestry Deconvolution for Next Generation Genomic Data" 
https://www.biorxiv.org/content/10.1101/2021.09.19.460980v1
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Launching in training mode...
Traceback (most recent call last):
  File "/Users/debortoli/Dropbox/Postdoc/brazil/hgdp/gnomix-main/gnomix.py", line 375, in <module>
    generations = config["simulation"]["gens"]
KeyError: 'gens'
(base) 

Do you know what this might be?

**Comment by weekend37** [comment] 2022-01-14 06:51
Ok I think I see where this could be coming from. Are you talking about the n_snps column? If so, you should not worry. That number should reflect the number of snps on the interval from the query file but in your case it might have reflected the query file that tis outputted when the phasing is performed. Quite subtle difference. 
This number should not matter at all but I guess it need not be this way.

Can you please try switching to this new branch:

`git checkout  phasing-format-copy`

and make sure you have the latest version

`git pull`

and see if you still get different results?

**Comment by weekend37** [comment] 2022-01-18 01:57
Glad I could help you with that. 

This next one must be because of extrapolation. As I have communicated somewhere to you before: 
I would advice you to **be careful with inference over large regions outside of the boundary of the training data.**
But with that said, this assertion shouldn't have been prompted - It should be fixed now.

Once more.... could you pull 

`git checkout phasing-format-copy
`

and make sure you have the latest version

`git pull
`

and try again?

**Comment by guidebortoli** [comment] 2022-01-18 12:29
Hi @weekend37,
I remember we had this conversation before (regarding the inference over large regions)...
As you can see above, I have:

Launching inference...
Loading and processing query file...
- Number of SNPs from model: 186554
- Number of SNPs from file: 308345
- Number of intersecting SNPs: 186554
- Percentage of model SNPs covered by query file: 100.0%

Would you suggest perhaps filtering the SNPs from file (308345), to reflect the number of SNPs in the query file? So I would have 186554 in the query and the same SNPs in the ref. file (which would still give the 100% SNPs covered by the query file)...

Thank you!

**Comment by weekend37** [comment] 2022-01-19 06:01
Yeah so it's a little bit tricky. I don't think **interpolation** is a problem, but do I think **extrapolation** is.
So the answer is ... **it depends**.

Let's say you have 5 SNPs in your model but 20 in your query file (including the same 5 SNPs as in the model).

If your non overlapping SNPs are spread over the same segment like this:
XOOOOXOOOXOOOOXOOOOX (X is both files, O is only in the query file)
you can trust the inference for your query file as the ancestry for the inner SNPs is **interpolated**.

Howeer, if the spread is something like this:
XXXXXOOOOOOOOOOOOOOO
you're in trouble because there isn't a good way to **extrapolate** the ancestry for the non overlapping SNPs. It's almost like you have an additional chromosome. You use chromosome 15a as reference and then infer over both 15a and 15b.

Right now, the .lai file should **extrapolate** it for you because it's designed to cover the same SNPs as your query file does. But this is not a good and it should give you a warning in that case.

So... If you have many query SNPs outside of the range of the reference SNPs I would do either:
- filter them out before doing the inference or
- just not believe the inference for those SNPs. The others are not affected by it anyways.. 
If all your SNPs are spread over the range of the reference SNPs however, you're good.

**Comment by guidebortoli** [comment] 2022-01-19 10:59
> Yeah so it's a little bit tricky. I don't think **interpolation** is a problem, but do I think **extrapolation** is. So the answer is ... **it depends**.
> 
> Let's say you have 5 SNPs in your model but 20 in your query file (including the same 5 SNPs as in the model).
> 
> If your non overlapping SNPs are spread over the same segment like this: XOOOOXOOOXOOOOXOOOOX (X is both files, O is only in the query file) you can trust the inference for your query file as the ancestry for the inner SNPs is **interpolated**.
> 
> Howeer, if the spread is something like this: XXXXXOOOOOOOOOOOOOOO you're in trouble because there isn't a good way to **extrapolate** the ancestry for the non overlapping SNPs. It's almost like you have an additional chromosome. You use chromosome 15a as reference and then infer over both 15a and 15b.
> 
> Right now, the .lai file should **extrapolate** it for you because it's designed to cover the same SNPs as your query file does. But this is not a good and it should give you a warning in that case.
> 
> So... If you have many query SNPs outside of the range of the reference SNPs I would do either:
> 
> * filter them out before doing the inference or
> * not believe the inference for those SNPs and just discard it. The others are not affected by it anyways.
>   If all your SNPs are spread over the range of the reference SNPs however, you're good.

Hi @weekend37 
Thank you for the clearly explanation!
Guilherme

**Comment by guidebortoli** [comment] 2022-01-24 12:40
Hi @weekend37,
This is not an issue but just an inquiring regarding the effect of the genetic map.
I believe we have discussed this months ago. I think you have told me that the genetic map does not need to include all the markers presented in the query file (or the model file, not sure).
But does it need to be within the query and model file?
For example:
First scenario: Let's say the query file start at position 190000; the model file starts at 189990 and the genetic map starts at 190010.
This would represent a problem?
Second scenario: Now let's say the query file start at position 190000; the model file starts at 189990 and the genetic map starts at 189995 (query within the genetic map but the model outside the genetic map)...
Third scenario: Query file start at position 190000; the model file starts at 189990 and the genetic map starts at 189980(query and model files within the genetic map)...

Thank you

**Comment by weekend37** [comment] 2022-05-29 16:10
First scenario: 
I assume you're training your own model. In that case, the model will extrapolate the positions not covered by the genetic map. That's not a big issue. When you then use the model for inference on the query file, you then cover the starting position on the query file so no issue.

Second scenario:
Same as first scenario.

Third scenario:
You have all the positional information to train the model without any extrapolation and your model covers the starting region of the query file. No issues :)

Let me emphasize two things:
- that the amount of which you extrapolate matters. For example in scenario one, it's worse if the starting position of the genetic map is 200000 than if it's 190010.
- all the issues in scenarios 1-3 are **extrapolations from the genetic map to model positions** which are by far better than **extrapolations from the model position to the query file positions**

Hope it helps.

- Helgi

**Closed** 2022-05-29 16:11 UTC
